
package mykeyboard;

import java.awt.*;
import javax.swing.*;

public class Mykeyboard
{
    public static void main(String[] args)
    {
        JFrame f = new JFrame();
        JPanel p = new JPanel();
        JTextField tf = new JTextField(1200);
        tf.setBounds(30,70,1285,30);
        JButton btn = new JButton("esc");
        JButton btn1 = new JButton("F1");
        JButton btn2 = new JButton("F2");
        JButton btn3 = new JButton("F3");
        JButton btn4 = new JButton("F4");
        JButton btn5 = new JButton("F5");
        JButton btn6 = new JButton("F6");
        JButton btn7 = new JButton("F7");
        JButton btn8 = new JButton("F8");
        JButton btn9 = new JButton("F9");
        JButton btn10 = new JButton("F10");
        JButton btn11 = new JButton("F11");
        JButton btn12 = new JButton("F12");
        JButton btn13 = new JButton("PrtSc");
        JButton btn14 = new JButton("Insert");
        JButton btn15 = new JButton("Delete");
        JButton btn16 = new JButton(">/||");
        JButton btn17 = new JButton("|<<");
        JButton btn18 = new JButton(">>|");
        JButton btn19 = new JButton("Start");
        JButton btn20 = new JButton("~");
        JButton btn21 = new JButton("1");
        JButton btn22 = new JButton("2");
        JButton btn23 = new JButton("3");
        JButton btn24 = new JButton("4");
        JButton btn25 = new JButton("5");
        JButton btn26 = new JButton("6");
        JButton btn27 = new JButton("7");
        JButton btn28 = new JButton("8");
        JButton btn29 = new JButton("9");
        JButton btn30 = new JButton("0");
        JButton btn31 = new JButton("_");
        JButton btn32 = new JButton("+");
        JButton btn33 = new JButton("Backspace");
        JButton btn34 = new JButton("NumLk");
        JButton btn35 = new JButton("/");
        JButton btn36 = new JButton("*");
        JButton btn37 = new JButton("-");
        JButton btn38 = new JButton("Tab");
        JButton btn39 = new JButton("Q");
        JButton btn40 = new JButton("W");
        JButton btn41 = new JButton("E");
        JButton btn42 = new JButton("R");
        JButton btn43 = new JButton("T");
        JButton btn44 = new JButton("Y");
        JButton btn45 = new JButton("U");
        JButton btn46 = new JButton("I");
        JButton btn47 = new JButton("O");
        JButton btn48 = new JButton("P");
        JButton btn49 = new JButton("{");
        JButton btn50 = new JButton("}");
        JButton btn51 = new JButton("|");
        JButton btn52 = new JButton("7");
        JButton btn53 = new JButton("8");
        JButton btn54 = new JButton("9");
        JButton btn55 = new JButton("+");
        JButton btn56 = new JButton("CapsLk");
        JButton btn57 = new JButton("A");
        JButton btn58 = new JButton("S");
        JButton btn59 = new JButton("D");
        JButton btn60 = new JButton("F");
        JButton btn61 = new JButton("G");
        JButton btn62 = new JButton("H");
        JButton btn63 = new JButton("J");
        JButton btn64 = new JButton("K");
        JButton btn65 = new JButton(":");
        JButton btn66 = new JButton("");
        JButton btn67 = new JButton("Enter");
        JButton btn68 = new JButton("4");
        JButton btn69 = new JButton("5");
        JButton btn70 = new JButton("6");
        JButton btn71 = new JButton("Shift");
        JButton btn72 = new JButton("Z");
        JButton btn73 = new JButton("X");
        JButton btn74 = new JButton("C");
        JButton btn75 = new JButton("V");
        JButton btn76 = new JButton("B");
        JButton btn77 = new JButton("N");
        JButton btn78 = new JButton("M");
        JButton btn79 = new JButton("<");
        JButton btn80 = new JButton(">");
        JButton btn81 = new JButton("?");
        JButton btn82 = new JButton("Shift");
        JButton btn83 = new JButton("1");
        JButton btn84 = new JButton("2");
        JButton btn85 = new JButton("3");
        JButton btn86 = new JButton("Enter");
        JButton btn87 = new JButton("Ctrl");
        JButton btn88 = new JButton("Fn");
        JButton btn89 = new JButton("Start");
        JButton btn90 = new JButton("Alt");
        JButton btn91 = new JButton("Space");
        JButton btn92 = new JButton("AltGr");
        JButton btn93 = new JButton("Ctrl");
        JButton btn94 = new JButton("Home");
        JButton btn95 = new JButton("PgUp");
        JButton btn96 = new JButton("PgDn");
        JButton btn97 = new JButton("End");
        JButton btn98 = new JButton("0");
        JButton btn99 = new JButton(".");
        
        f.add(p);
      // p.setLayout(null);
        p.add(tf);
        p.add(btn);
        p.add(btn1);
        p.add(btn2);
        p.add(btn3);
        p.add(btn4);
        p.add(btn5);
        p.add(btn6);
        p.add(btn7);
        p.add(btn8);
        p.add(btn9);
        p.add(btn10);
        p.add(btn11);
        p.add(btn12);
        p.add(btn13);
        p.add(btn14);
        p.add(btn15);
        p.add(btn16);
        p.add(btn17);
        p.add(btn18);
        p.add(btn19);
        p.add(btn20);
        p.add(btn21);
        p.add(btn22);
        p.add(btn23);
        p.add(btn24);
        p.add(btn25);
        p.add(btn26);
        p.add(btn27);
        p.add(btn28);
        p.add(btn29);
        p.add(btn30);
        p.add(btn31);
        p.add(btn32);
        p.add(btn33);
        p.add(btn34);
        p.add(btn35);
        p.add(btn36);
        p.add(btn37);
        p.add(btn38);
        p.add(btn39);
        p.add(btn40);
        p.add(btn41);
        p.add(btn42);
        p.add(btn43);
        p.add(btn44);
        p.add(btn45);
        p.add(btn46);
        p.add(btn47);
        p.add(btn48);
        p.add(btn49);
        p.add(btn50);
        p.add(btn51);
        p.add(btn52);
        p.add(btn53);
        p.add(btn54);
        p.add(btn55);
        p.add(btn56);
        p.add(btn57);
        p.add(btn58);
        p.add(btn59);
        p.add(btn60);
        p.add(btn61);
        p.add(btn62);
        p.add(btn63);
        p.add(btn64);
        p.add(btn65);
        p.add(btn66);
        p.add(btn67);
        p.add(btn68);
        p.add(btn69);
        p.add(btn70);
        p.add(btn71);
        p.add(btn72);
        p.add(btn73);
        p.add(btn74);
        p.add(btn75);
        p.add(btn76);
        p.add(btn77);
        p.add(btn78);
        p.add(btn79);
        p.add(btn80);
        p.add(btn81);
        p.add(btn82);
        p.add(btn83);
        p.add(btn84);
        p.add(btn85);
        p.add(btn86);
        p.add(btn87);
        p.add(btn88);
        p.add(btn89);
        p.add(btn90);
        p.add(btn91);
        p.add(btn92);
        p.add(btn93);
        p.add(btn94);
        p.add(btn95);
        p.add(btn96);
        p.add(btn97);
        p.add(btn98);
        p.add(btn99);
        f.setSize(1500,1000);
        f.setBackground(Color.black);
        f.setVisible(true);
    }
}